export const SHOPPING_LIST = [
  {
    id: "1",
    category: "outer",
    title: "가디건",
    price: 26930,
    image: "./assets/img/outer-cardigan.png",
  },
  {
    id: "2",
    category: "outer",
    title: "후드집업",
    price: 69700,
    image: "./assets/img/outer-hooded.png",
  },
  {
    id: "3",
    category: "outer",
    title: "가죽자켓",
    price: 45900,
    image: "./assets/img/outer-leather.png",
  },
  {
    id: "4",
    category: "outer",
    title: "바람막이",
    price: 44000,
    image: "./assets/img/outer-windbreaker.png",
  },
  {
    id: "5",
    category: "top",
    title: "니트 - 핑크",
    price: 28500,
    image: "./assets/img/top-knitwear-pink.png",
  },
  {
    id: "6",
    category: "top",
    title: "티셔츠 - 블랙",
    price: 11000,
    image: "./assets/img/top-shirt-black.png",
  },
  {
    id: "7",
    category: "top",
    title: "셔츠 - 연보라",
    price: 17100,
    image: "./assets/img/top-shirt-white.png",
  },
  {
    id: "8",
    category: "top",
    title: "셔츠 - 화이트",
    price: 50000,
    image: "./assets/img/top-shirt-white.png",
  },
  {
    id: "9",
    category: "top",
    title: "긴팔티 - 화이트",
    price: 21000,
    image: "./assets/img/top-sleeved-shirt-white.png",
  },
  {
    id: "10",
    category: "pants",
    title: "와이드 카고",
    price: 19400,
    image: "./assets/img/pants-cargo.png",
  },
  {
    id: "11",
    category: "pants",
    title: "데님 팬츠",
    price: 29900,
    image: "./assets/img/pants-denim.png",
  },
];
